### ISSUE TITLE
Immediate saving of Song `/path/to/YYYYMMDD-hhmmss.xrns`

### ISSUE THREAD

**Issue by tkna91** [esaruoho/paketti#702]
I want to immediately save a song file that I improvised during a live performance, for example.
If I compose a song during a live performance and have already finished playing it, I want to quickly save it, open another song file, and immediately move on to the next task (e.g., adjusting the volume of each song by monitor listening with headphones).

In the first version, the only information the user would need to specify would be the destination directory.
Sorry, but the file name is fine with a fixed timestamp (YYYYYMMDD-hhmmss) at the time, and I want something usable as soon as possible.
Various other possible options could be considered as upgrades after that first release.

https://github.com/user-attachments/assets/3a42fb27-a458-40e4-9e50-59f7107bc2c0

**Comment by esaruoho** [comment]
<img width="930" alt="Screenshot 2024-11-16 at 9 23 38" src="https://github.com/user-attachments/assets/4ba56a09-6f9d-484b-a0e1-b8c83d2a91fa">
