### ISSUE TITLE
Set the output of the CURRENT/MASTER channel to full L or R

### ISSUE THREAD

**Issue by tkna91** [esaruoho/paketti#715]
In studio sessions, it is sometimes useful to view the stereo output as two monaural channels that can be divided into separate channels, rather than for listening with the left and right ears, as it makes it easier to play different sounds on multiple amplifiers and speakers.

For such needs, the following functions would be useful

- Set Pan to L for the CURRENT track
- Set Pan to R for the CURRENT track
- Set Pan to L for the MASTER track
- Set Pan to R for the MASTER track

https://github.com/user-attachments/assets/60932a10-910d-4bcd-a055-c7bb3dd6bcb4

**Comment by esaruoho** [comment]
you forgot center
<img width="656" alt="Screenshot 2024-12-07 at 19 46 05" src="https://github.com/user-attachments/assets/f0a706b5-830e-4f6e-be1f-6b3cd58fb272">
<img width="331" alt="Screenshot 2024-12-07 at 19 46 25" src="https://github.com/user-attachments/assets/9ad5a012-3c2a-49e0-b589-7ba24cf7a729">
