### ISSUE TITLE
Switch track scope/spectrum

### ISSUE THREAD

**Issue by tkna91** [esaruoho/paketti#739]
As well as `Switch to Automation`,
It would be useful to be able to switch between `track scope` and `spectrum pane`.

https://github.com/user-attachments/assets/86ce1740-09b8-4fce-aa6e-b376b3ce595e

**Comment by esaruoho** [comment]
<img width="355" alt="Screenshot 2024-12-07 at 14 33 24" src="https://github.com/user-attachments/assets/9b7e209c-2e1c-47b0-9977-21f542df003f">
